services:
  - type: web
    name: chainlit-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
